---
title: "STAP DND Mixed Effects"
author: "Adam Peterson"
date: "3/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
set.seed(24)
num_subj <- 100
num_bef <- 10
Z <- rep(rbinom(n = num_subj, size = 1, prob = .5),3)
delta <- -.5
theta_s <- 0.5
alpha <- 22
beta <- 1.2
beta_bar <- 1
sigma <- .9
sigma_b <- 1.5
dists_1 <- matrix(rexp(n = num_subj*num_bef,
                       rate = 1),
                  nrow = num_subj,
                  ncol = num_bef)
dists_2 <- matrix(rexp(n = num_subj*num_bef,
                       rate = 1),
                  nrow = num_subj,
                  ncol = num_bef)
dists_3 <- matrix(rexp(n= num_subj*num_bef,
                       rate = .5),
                  nrow = num_subj, ncol = num_bef)
dists <- rbind(dists_1,dists_2,dists_3)
colnames(dists) <- stringr::str_c("BEF_",1:ncol(dists))
dists <- as_tibble(dists)

dists <- dists %>% mutate(id=expand.grid(subj=1:num_subj,time = 1:3)$subj,
                         time = expand.grid(1:num_subj,time = 1:3)$time) %>%
    gather(contains("BEF"),key = "BEF", value="Distance") %>% 
    filter(Distance<=5)

X <- dists %>% group_by(id,time) %>% summarise(Exposure = sum(exp(-Distance/theta_s)))
X_bar <- X %>% group_by(id) %>% summarise(MN_Exposure = mean(Exposure)) %>% 
    mutate(subj_int = rnorm(n = num_subj,
                            mean = 0,
                            sd = sigma_b),
           subj_slope = rnorm(n=num_subj,0,1))

X_diff <- X %>% left_join(X_bar,by='id') %>% mutate(X_diff = Exposure - MN_Exposure)

epsilon_ij <- rnorm(n = num_subj * 3, mean = 0, sd = sigma)

eta <- alpha + 
    Z * delta +
    beta*X_diff$X_diff + 
    X_diff$MN_Exposure*beta_bar + 
    X_diff$subj_int + X_diff$subj_slope * X_diff$time 

y <- eta + epsilon_ij 

Z <- matrix(Z,ncol=1)
```

```{r}
dists_crs <- matrix(dists %>% arrange(id,time) %>% select(Distance) %>% pull(),nrow=1)
u_crs <- as_tibble(xtabs(~id + time,data = dists, addNA = T)) %>% 
    mutate(id = as.integer(id),time = as.integer(time)) %>% 
    arrange(id,time) %>% 
    mutate(start = replace(dplyr::lag(cumsum(n)),is.na(dplyr::lag(cumsum(n))),0)+1,
           stop = cumsum(n)) %>% select(start,stop) %>% mutate(start = start - 1,
                                                               stop = stop - 1)

subj_mat1 <- as.matrix(Matrix::fac2sparse(as.factor(X_diff$id)))
subj_mat2 <- subj_mat1 %*% diag(X_diff$time)
subj_n <- rep(1/3,num_subj)
W <- subj_mat2
```


```{r}
iter_max <- 150
warmup <- 75
sink("~/Desktop/Routput.txt")
fit <- stapdnd_glmer(y = y, Z = Z,W = W,
                     u_crs = as.matrix(u_crs),
                      subj_matrix = subj_mat1,
                      subj_n = matrix(subj_n,ncol=1),
                      stap_par_code = c(length(y),1,1,1,num_subj,2),
                      distances = dists_crs,
                      adapt_delta = .65,
                      warmup = warmup, 
                      iter_max = iter_max,
                      max_treedepth = 10,
                      seed = 4423,
                      diagnostics = 0)
sink()
```



```{r}
samples <- tibble(chain=1,
                  alpha = fit$alpha_samps,
                  delta = fit$delta_samps[,1],
                  beta = fit$beta_samps[,1],
                  beta_bar = fit$beta_bar_samps[,1],
                  theta = fit$theta_samps,
                  sigma = fit$sigma_samps,
                  Sigma = sqrt(fit$Sigma_samps[,1]),
                  Sigma_2 = sqrt(fit$Sigma_samps[,4]),
                  rho = purrr::map_dbl(1:iter_max,function(x) cov2cor(matrix(fit$Sigma_samps[x,],nrow=2,ncol=2))[1,2]),
                  acceptance = fit$acceptance) %>% mutate(ix = 1:n())
```


```{r}
samples %>% filter(acceptance==1,ix>warmup) %>% 
    gather(delta,beta,beta_bar,theta,sigma,alpha,Sigma_2,rho,
           Sigma,key="Parameters",value="Samples") %>% 
    mutate(Truth = (Parameters=="beta")*beta +
               (Parameters =="theta")*theta_s +
               (Parameters=="sigma")*sigma + 
               (Parameters=="delta") *delta +
               (Parameters=="beta_bar")*beta_bar +
               (Parameters=="Sigma")*sigma_b +  
               (Parameters=="Sigma_2")*1+
               (Parameters=="rho")*0 +
               (Parameters=="alpha")*alpha) %>% 
    ggplot(aes(x=Samples)) + geom_density() + theme_bw() + 
    geom_vline(aes(xintercept=Truth),linetype=2) +
    facet_wrap(~Parameters,scales="free") + ggtitle("Custom NUTS - Posterior Samples") + 
    theme(strip.background = element_blank())
```


```{r}
median_bs <- apply(fit$b_int_samps,2,median)
plot(X_bar$subj_int,median_bs)
abline(a=0,b=1)
```


```{r}
median_bs <- apply(fit$b_int_samps,2,median)
plot(X_bar$subj_int,median_bs)
abline(a=0,b=1)
```



```{r,echo = F}
sigma_bs <- seq(from = 0,to=25,by=1)
sink("~/Desktop/Routput.txt")
out <- test_grads_glmer(y,Z,W,
                        true_b = as.matrix(X_bar[,c("subj_int","subj_slope")]),
                        beta_bar,beta,
                        dists_crs,as.matrix(u_crs),
                        subj_mat1,as.matrix(subj_n,ncol=1),
                        sigma_bs,
                        c(length(y),1,1,1,num_subj,2),
                        seed = 1241)
sink()

tibble(subj_sigma = sigma_bs,
       energy = out$energy) %>%
    ggplot(aes(x=subj_sigma,y=energy)) + geom_line() + theme_bw()  + 
    geom_vline(aes(xintercept = 22) ,linetype = 2)

```


```{r,echo=F}
tibble(sbs = sigma_bs,
       grad = out$grad) %>%
    ggplot(aes(x=sbs,y=grad)) + geom_line() + theme_bw()  + geom_vline(aes(xintercept = 22) ,linetype = 2)
```

