// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// stap_diffndiff
Rcpp::List stap_diffndiff(Eigen::VectorXd& y, Eigen::VectorXd& beta, Eigen::VectorXd& theta, Eigen::MatrixXd& distances, Eigen::MatrixXd& d_one, Eigen::MatrixXd& d_two, Eigen::MatrixXd& d_three, const double adapt_delta, const int iter_max, const int warmup, const int seed);
RcppExport SEXP _rstap2_stap_diffndiff(SEXP ySEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP distancesSEXP, SEXP d_oneSEXP, SEXP d_twoSEXP, SEXP d_threeSEXP, SEXP adapt_deltaSEXP, SEXP iter_maxSEXP, SEXP warmupSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type d_one(d_oneSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type d_two(d_twoSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type d_three(d_threeSEXP);
    Rcpp::traits::input_parameter< const double >::type adapt_delta(adapt_deltaSEXP);
    Rcpp::traits::input_parameter< const int >::type iter_max(iter_maxSEXP);
    Rcpp::traits::input_parameter< const int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(stap_diffndiff(y, beta, theta, distances, d_one, d_two, d_three, adapt_delta, iter_max, warmup, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rstap2_stap_diffndiff", (DL_FUNC) &_rstap2_stap_diffndiff, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_rstap2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
