# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stap_diffndiff <- function(y, Z, distances, u_crs, subj_array, subj_n, stap_par_code, adapt_delta, iter_max, max_treedepth, warmup, seed, diagnostics) {
    .Call(`_rstap2_stap_diffndiff`, y, Z, distances, u_crs, subj_array, subj_n, stap_par_code, adapt_delta, iter_max, max_treedepth, warmup, seed, diagnostics)
}

test_grads <- function(y, Z, beta_bar, beta, distances, u_crs, subj_array, subj_n, par_grid, stap_par_code, seed) {
    .Call(`_rstap2_test_grads`, y, Z, beta_bar, beta, distances, u_crs, subj_array, subj_n, par_grid, stap_par_code, seed)
}

#'Estimates a STAP model with random subject intercept only
stapdnd_glmer <- function(y, Z, W, distances, u_crs, subj_matrix, subj_n, stap_par_code, adapt_delta, iter_max, max_treedepth, warmup, seed, diagnostics) {
    .Call(`_rstap2_stapdnd_glmer`, y, Z, W, distances, u_crs, subj_matrix, subj_n, stap_par_code, adapt_delta, iter_max, max_treedepth, warmup, seed, diagnostics)
}

#'Estimates a STAP model with random subject intercept and slope 
stapdnd_glmer2 <- function(y, Z, W, eta, distances, u_crs, subj_matrix, subj_n, stap_par_code, adapt_delta, iter_max, max_treedepth, warmup, seed, diagnostics) {
    .Call(`_rstap2_stapdnd_glmer2`, y, Z, W, eta, distances, u_crs, subj_matrix, subj_n, stap_par_code, adapt_delta, iter_max, max_treedepth, warmup, seed, diagnostics)
}

test_grads_glmer <- function(y, Z, W, true_b, beta_bar, beta, distances, u_crs, subj_array, subj_n, par_grid, stap_par_code, seed) {
    .Call(`_rstap2_test_grads_glmer`, y, Z, W, true_b, beta_bar, beta, distances, u_crs, subj_array, subj_n, par_grid, stap_par_code, seed)
}

